### ISSUE TITLE
Script wont run "const next = response.data.meta.pagination.cursors?.next;"

### ISSUE THREAD

**Issue by fttdgc** [dmtkpv/patreon-downloader#1]
After following the instructions and attempting to run, the error below is generated,

`const next = response.data.meta.pagination.cursors?.next;
                                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47`

**Comment by dmtkpv** [comment]
Your Node.js version does not support optional chaining. \
Please upgrade to Node.js 14+.
